Improve working with the "show more banks" button.
dontgiveafish/hryvna-today pull request #26
Opened 2019-01-18 14:53 UTC by sarapuka

Fixed inappropriate title of the expand button after changing the currency.

2019-01-23 14:25 UTC, abagayev requested changes

2019-01-23 14:25 UTC, abagayev commented on engine/views/templates/site.tpl
> +<script src="js/functions.js?v=6"></script>
v6

2019-01-23 14:25 UTC, abagayev commented on engine/public/hryvna.today/js/functions.js
> +    showMoreBanksButton.init();
можна було залишити `showMoreBanks()` и в ньому викликати `showMoreBanksButton.init();`, щоб не порушувати інтерфейс і не робити тут зміни

2019-01-23 17:17 UTC, sarapuka commented on engine/views/templates/site.tpl
> +<script src="js/functions.js?v=6"></script>
Виправив :heavy_check_mark:

2019-01-23 17:17 UTC, sarapuka commented on engine/public/hryvna.today/js/functions.js
> +    showMoreBanksButton.init();
Виправив :heavy_check_mark:

2019-04-02 16:06 UTC, abagayev approved these changes

2019-04-02 16:06 UTC, merged